'use client';

import { motion } from 'framer-motion';

const features = [
  'Smart expense splits',
  'Automatic balance tracking',
  'Settle-up suggestions',
  'Receipt uploads',
];

const faqs = [
  {
    q: 'How does FairShare calculate balances?',
    a: 'All balances are computed server-side from expense splits and settlements using cent-precision amounts.',
  },
  {
    q: 'Can I upload receipts?',
    a: 'Yes, receipt uploads use secure presigned S3 URLs generated by the backend.',
  },
  {
    q: 'Is there a free plan?',
    a: 'Yes. MVP is free while we build pro features.',
  },
];

export default function HomePage() {
  return (
    <main className="min-h-screen">
      <section className="mx-auto max-w-6xl px-6 py-20">
        <motion.h1 initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} className="text-5xl font-bold tracking-tight">
          Split smarter with FairShare
        </motion.h1>
        <p className="mt-4 max-w-2xl text-lg text-slate-600">Track group expenses, simplify debts, and settle transparently.</p>
        <div className="mt-8 flex gap-4">
          <a href="/login" className="rounded bg-brand px-5 py-3 text-white">Get Started</a>
          <a href="/features" className="rounded border border-slate-300 px-5 py-3">View Features</a>
        </div>
      </section>

      <section className="mx-auto max-w-6xl px-6 pb-16">
        <h2 className="text-3xl font-semibold">Product Screenshots</h2>
        <div className="mt-6 grid gap-4 md:grid-cols-3">
          {['Dashboard', 'Group Detail', 'Settle Up'].map((label) => (
            <div key={label} className="rounded-xl border border-slate-200 bg-white p-3 shadow-sm">
              <div className="h-48 rounded bg-gradient-to-br from-indigo-100 to-slate-100" />
              <p className="mt-3 text-sm font-medium text-slate-700">{label}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="mx-auto max-w-6xl px-6 pb-16">
        <h2 className="text-3xl font-semibold">Features</h2>
        <div className="mt-6 grid gap-4 md:grid-cols-2">
          {features.map((item, index) => (
            <motion.div
              key={item}
              initial={{ opacity: 0, y: 12 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: index * 0.05 }}
              className="rounded-lg border border-slate-200 bg-white p-4"
            >
              {item}
            </motion.div>
          ))}
        </div>
      </section>

      <section className="mx-auto max-w-6xl px-6 pb-16">
        <h2 className="text-3xl font-semibold">Feature Comparison</h2>
        <div className="mt-6 overflow-x-auto rounded-lg border border-slate-200 bg-white">
          <table className="min-w-full text-left text-sm">
            <thead className="bg-slate-100">
              <tr>
                <th className="px-4 py-3">Feature</th>
                <th className="px-4 py-3">FairShare</th>
                <th className="px-4 py-3">Spreadsheets</th>
              </tr>
            </thead>
            <tbody>
              <tr className="border-t border-slate-200"><td className="px-4 py-3">Auto balances</td><td className="px-4 py-3">Yes</td><td className="px-4 py-3">Manual</td></tr>
              <tr className="border-t border-slate-200"><td className="px-4 py-3">Settlement suggestions</td><td className="px-4 py-3">Yes</td><td className="px-4 py-3">No</td></tr>
              <tr className="border-t border-slate-200"><td className="px-4 py-3">Receipt uploads</td><td className="px-4 py-3">Yes</td><td className="px-4 py-3">No</td></tr>
            </tbody>
          </table>
        </div>
      </section>

      <section className="mx-auto max-w-6xl px-6 pb-16">
        <h2 className="text-3xl font-semibold">FAQ</h2>
        <div className="mt-6 space-y-3">
          {faqs.map((faq) => (
            <div key={faq.q} className="rounded-lg border border-slate-200 bg-white p-4">
              <h3 className="font-semibold">{faq.q}</h3>
              <p className="mt-2 text-slate-600">{faq.a}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="mx-auto max-w-6xl px-6 pb-20">
        <div className="rounded-xl border border-slate-200 bg-white p-6">
          <h2 className="text-2xl font-semibold">Newsletter</h2>
          <p className="mt-2 text-slate-600">Get product updates and beta invitations.</p>
          <form className="mt-4 flex flex-col gap-3 sm:flex-row">
            <input type="email" placeholder="Enter your email" className="w-full rounded border border-slate-300 px-4 py-3" />
            <button className="rounded bg-brand px-5 py-3 text-white" type="submit">Subscribe</button>
          </form>
        </div>
      </section>

      <footer className="border-t border-slate-200 bg-white">
        <div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-6">
          <p>FairShare</p>
          <div className="flex gap-4 text-sm text-slate-600">
            <a href="/about">About</a>
            <a href="/pricing">Pricing</a>
            <a href="/login">Login</a>
          </div>
        </div>
      </footer>
    </main>
  );
}
