'use client';

import { motion } from 'framer-motion';
import { MoveRight, CheckCircle2, Zap, Shield, TrendingUp } from 'lucide-react';

const features = [
  { text: 'Smart expense splits', icon: Zap, color: 'text-yellow-400' },
  { text: 'Automatic balance tracking', icon: TrendingUp, color: 'text-cyan-400' },
  { text: 'Settle-up suggestions', icon: CheckCircle2, color: 'text-purple-400' },
  { text: 'Receipt uploads', icon: Shield, color: 'text-pink-400' },
];

const faqs = [
  {
    q: 'How does FairShare calculate balances?',
    a: 'All balances are computed server-side from expense splits and settlements using cent-precision amounts.',
  },
  {
    q: 'Can I upload receipts?',
    a: 'Yes, receipt uploads use secure presigned S3 URLs generated by the backend.',
  },
  {
    q: 'Is there a free plan?',
    a: 'Yes. MVP is free while we build pro features.',
  },
];

export default function HomePage() {
  return (
    <main className="relative min-h-screen font-sans text-white">
      {/* Hero Section */}
      <section className="mx-auto max-w-7xl px-6 py-32 text-center md:py-48">
        <motion.div
          initial={{ opacity: 0, scale: 0.9 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.5 }}
          className="relative inline-block"
        >
          <h1 
            data-text="FAIRSHARE"
            className="glitch-text text-7xl font-black italic tracking-tighter md:text-9xl lg:text-[12rem]"
          >
            FAIRSHARE
          </h1>
        </motion.div>
        
        <motion.p 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
          className="mx-auto mt-6 max-w-2xl text-xl font-bold uppercase tracking-widest text-zinc-400 md:text-3xl"
        >
          Split smarter. Settle faster. <span className="text-white italic underline decoration-yellow-400 decoration-4 underline-offset-8">No cap.</span>
        </motion.p>

        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.4 }}
          className="mt-12 flex flex-col items-center justify-center gap-6 sm:flex-row"
        >
          <a
            href="/login"
            className="neo-pop-hover neo-pop-hover-purple group relative flex items-center gap-3 border-2 border-white bg-white px-8 py-4 font-black text-black transition-colors hover:bg-transparent hover:text-white"
          >
            GET STARTED <MoveRight className="group-hover:translate-x-2 transition-transform" />
          </a>
          <a
            href="/features"
            className="neo-pop-hover neo-pop-hover-cyan flex items-center gap-3 border-2 border-white bg-black px-8 py-4 font-black transition-all"
          >
            SYSTEM FEATURES
          </a>
        </motion.div>
      </section>

      {/* Social Proof / Features Grid */}
      <section className="mx-auto max-w-7xl px-6 pb-32">
        <h2 className="mb-12 text-center text-4xl font-black uppercase italic tracking-tighter text-yellow-400 md:text-6xl">
          Core Mechanics
        </h2>
        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4">
          {features.map((item, index) => (
            <motion.div
              key={item.text}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: index * 0.1 }}
              className="neo-border neo-shadow-purple neo-pop-hover bg-zinc-900 p-8"
            >
              <item.icon size={48} className={`mb-6 ${item.color}`} />
              <h3 className="text-xl font-black uppercase leading-tight">
                {item.text}
              </h3>
            </motion.div>
          ))}
        </div>
      </section>

      {/* Pricing / Table (Feature Comparison) */}
      <section className="mx-auto max-w-7xl px-6 pb-32">
        <div className="neo-border neo-shadow-cyan bg-black p-8 md:p-12">
          <h2 className="mb-12 text-4xl font-black uppercase italic tracking-tighter text-cyan-400 md:text-6xl text-center md:text-left">
            Meta vs Reality
          </h2>
          <div className="overflow-x-auto">
            <table className="w-full text-left font-bold uppercase tracking-tighter">
              <thead className="border-b-4 border-white">
                <tr>
                  <th className="px-4 py-6 text-2xl">Standard</th>
                  <th className="px-4 py-6 text-2xl text-yellow-400">FairShare</th>
                  <th className="px-4 py-6 text-2xl text-zinc-500">Spreadsheets</th>
                </tr>
              </thead>
              <tbody className="divide-y-2 divide-zinc-800">
                <tr>
                  <td className="px-4 py-6">Auto balances</td>
                  <td className="px-4 py-6 text-white">Full Send</td>
                  <td className="px-4 py-6 text-zinc-500">Manual L</td>
                </tr>
                <tr>
                  <td className="px-4 py-6">Settle up</td>
                  <td className="px-4 py-6 text-white">One Tap</td>
                  <td className="px-4 py-6 text-zinc-500">N/A</td>
                </tr>
                <tr>
                  <td className="px-4 py-6">Receipts</td>
                  <td className="px-4 py-6 text-white">Cloud Base</td>
                  <td className="px-4 py-6 text-zinc-500">Physical Only</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="mx-auto max-w-4xl px-6 pb-32">
        <h2 className="mb-12 text-center text-4xl font-black uppercase italic tracking-tighter text-pink-500 md:text-6xl">
          Dev Log
        </h2>
        <div className="space-y-6">
          {faqs.map((faq) => (
            <div key={faq.q} className="neo-border neo-shadow-yellow bg-zinc-900 p-6">
              <h3 className="text-lg font-black uppercase tracking-tighter md:text-2xl">
                {faq.q}
              </h3>
              <p className="mt-4 font-bold text-zinc-400">
                {faq.a}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* Newsletter / CTA */}
      <section className="mx-auto max-w-7xl px-6 pb-48">
        <div className="neo-border bg-white px-8 py-12 text-black md:px-20 md:py-24 text-center">
          <h2 className="text-5xl font-black uppercase italic tracking-tighter md:text-8xl">
            LOCK IN.
          </h2>
          <p className="mt-6 text-xl font-bold uppercase tracking-widest text-zinc-600">
            Join the beta and stop the group chat static.
          </p>
          <form className="mt-12 flex flex-col gap-4 md:flex-row md:justify-center">
            <input 
              type="email" 
              placeholder="YOUR@EMAIL.XYZ" 
              className="border-4 border-black bg-white px-6 py-4 font-black uppercase placeholder-zinc-400 outline-none focus:bg-yellow-100 transition-colors md:min-w-[400px]" 
            />
            <button 
              type="submit"
              className="neo-pop-hover bg-black px-10 py-4 font-black uppercase text-white shadow-[4px_4px_0px_0px_rgba(168,85,247,1)]"
            >
              SUBSCRIBE
            </button>
          </form>
        </div>
      </section>

      <footer className="border-t-4 border-white bg-black py-12 px-6">
        <div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-8 md:flex-row">
          <p className="text-3xl font-black uppercase tracking-tighter italic">FAIRSHARE</p>
          <div className="flex gap-12 font-black uppercase tracking-widest text-zinc-500 hover:text-white transition-colors">
            <a href="/about" className="hover:text-yellow-400">About</a>
            <a href="/pricing" className="hover:text-cyan-400">Pricing</a>
            <a href="/login" className="hover:text-purple-400">Login</a>
          </div>
        </div>
      </footer>
    </main>
  );
}

