aws_region            = "ap-south-1"
environment           = "staging"
vpc_cidr              = "10.20.0.0/16"
availability_zones    = ["ap-south-1a", "ap-south-1b"]
s3_bucket_name        = "fairshare-staging-receipts"
backend_image         = "123456789012.dkr.ecr.ap-south-1.amazonaws.com/fairshare-backend:staging"
backend_desired_count = 1
backend_min_capacity  = 1
backend_max_capacity  = 3
